name: CI

on:
  push:
    branches: ["main"] 
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install C libraries on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev libarchive-dev

      - name: Install C libraries on macOS
        if: startsWith(matrix.os, 'macos')
        run: brew install zlib libarchive

      - uses: leanprover/lean-action@v1

      - name: Run tests
        run: lake exe tencert
